### ISSUE TITLE
http://localhost/easyappointments/ - Undefined variable php error

### ISSUE THREAD

**Issue by jrmengineeringconsultants** [smullolo/easy-appointments#57]
A PHP Error was encountered
Severity: Notice

Message: Undefined variable: company_name

Filename: appointments/book.php

Line Number: 30

1
2
3
4
A PHP Error was encountered
Severity: Notice

Message: Undefined variable: manage_mode

Filename: appointments/book.php

Line Number: 49

Unexpected Issues
$name setting does not exist in database: company_name
#0 C:\xampp\htdocs\eCalendar\application\controllers\Appointments.php(76): Settings_Model->get_setting('company_name')
#1 C:\xampp\htdocs\eCalendar\system\core\CodeIgniter.php(532): Appointments->index()
#2 C:\xampp\htdocs\eCalendar\index.php(353): require_once('C:\\xampp\\htdocs...')
#3 {main}
Select Service & Provider
Select Service 
Select Provider 
Next
Powered By Easy!Appointments | English | Login
A PHP Error was encountered
Severity: Notice

Message: Undefined variable: display_cookie_notice

Filename: appointments/book.php

Line Number: 352

A PHP Error was encountered
Severity: Notice

Message: Undefined variable: display_terms_and_conditions

Filename: appointments/book.php

Line Number: 356

A PHP Error was encountered
Severity: Notice

Message: Undefined variable: display_privacy_policy

Filename: appointments/book.php

Line Number: 360

**Comment by jrmengineeringconsultants** [comment]
Please help me display the calendar
